name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install npm 9
        run: npm install -g npm@9

      - name: Install dependencies
        run: npm ci

      - name: "Run tests (with Github Actions wireit cache)"
        run: npm run qa
